scala_library(name='beer-server',
  sources=globs('*.scala'),

  dependencies=[
    'thrift/com/fzakaria/beer:beer-scala',
    '3rdparty/jvm/com/twitter/finatra:finatra-thrift',
  	'3rdparty/jvm/com/twitter/finatra:finatra-http',
  	'3rdparty/jvm/com/twitter/finatra:finatra-utils'
  ],

)